/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GafcoreRouteImport } from './routes/gafcore'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GafcoreRegisterRouteImport } from './routes/gafcore_.register'
import { Route as GafcoreProjectsRouteImport } from './routes/gafcore_.projects'
import { Route as GafcoreLoginRouteImport } from './routes/gafcore_.login'
import { Route as GafcoreAppRouteImport } from './routes/gafcore_.app'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as GafcoreSettingsProjectRouteImport } from './routes/gafcore_.settings.project'
import { Route as ApiV1MeRouteImport } from './routes/api/v1/me'
import { Route as ApiV1KeysRouteImport } from './routes/api/v1/keys'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1GenerationsRouteImport } from './routes/api/v1/generations'
import { Route as ApiV1CreditsRouteImport } from './routes/api/v1/credits'
import { Route as ApiV1OpenapiJsonRouteImport } from './routes/api/v1/openapi.json'
import { Route as ApiV1KeysIdRouteImport } from './routes/api/v1/keys.$id'
import { Route as ApiV1AiGenerateRouteImport } from './routes/api/v1/ai.generate'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicGafcoreSupportFaqRouteImport } from './routes/api/public/gafcore.support-faq'
import { Route as ApiPublicBillingCheckRouteImport } from './routes/api/public/billing.check'
import { Route as ApiGafcoreChatStreamRouteImport } from './routes/api/gafcore/chat.stream'
import { Route as ApiGafcoreCheckoutSessionRouteImport } from './routes/api/gafcore/checkout-session'
import { Route as ApiGafcoreCheckoutConfirmRouteImport } from './routes/api/gafcore/checkout-confirm'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GafcoreRoute = GafcoreRouteImport.update({
  id: '/gafcore',
  path: '/gafcore',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GafcoreRegisterRoute = GafcoreRegisterRouteImport.update({
  id: '/gafcore_/register',
  path: '/gafcore/register',
  getParentRoute: () => rootRouteImport,
} as any)
const GafcoreProjectsRoute = GafcoreProjectsRouteImport.update({
  id: '/gafcore_/projects',
  path: '/gafcore/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const GafcoreLoginRoute = GafcoreLoginRouteImport.update({
  id: '/gafcore_/login',
  path: '/gafcore/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GafcoreAppRoute = GafcoreAppRouteImport.update({
  id: '/gafcore_/app',
  path: '/gafcore/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const GafcoreSettingsProjectRoute = GafcoreSettingsProjectRouteImport.update({
  id: '/gafcore_/settings/project',
  path: '/gafcore/settings/project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MeRoute = ApiV1MeRouteImport.update({
  id: '/api/v1/me',
  path: '/api/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1KeysRoute = ApiV1KeysRouteImport.update({
  id: '/api/v1/keys',
  path: '/api/v1/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GenerationsRoute = ApiV1GenerationsRouteImport.update({
  id: '/api/v1/generations',
  path: '/api/v1/generations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CreditsRoute = ApiV1CreditsRouteImport.update({
  id: '/api/v1/credits',
  path: '/api/v1/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpenapiJsonRoute = ApiV1OpenapiJsonRouteImport.update({
  id: '/api/v1/openapi/json',
  path: '/api/v1/openapi/json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1KeysIdRoute = ApiV1KeysIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1KeysRoute,
} as any)
const ApiV1AiGenerateRoute = ApiV1AiGenerateRouteImport.update({
  id: '/api/v1/ai/generate',
  path: '/api/v1/ai/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGafcoreSupportFaqRoute =
  ApiPublicGafcoreSupportFaqRouteImport.update({
    id: '/api/public/gafcore/support-faq',
    path: '/api/public/gafcore/support-faq',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBillingCheckRoute = ApiPublicBillingCheckRouteImport.update({
  id: '/api/public/billing/check',
  path: '/api/public/billing/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGafcoreChatStreamRoute = ApiGafcoreChatStreamRouteImport.update({
  id: '/api/gafcore/chat/stream',
  path: '/api/gafcore/chat/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGafcoreCheckoutSessionRoute = ApiGafcoreCheckoutSessionRouteImport.update({
  id: '/api/gafcore/checkout-session',
  path: '/api/gafcore/checkout-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGafcoreCheckoutConfirmRoute = ApiGafcoreCheckoutConfirmRouteImport.update({
  id: '/api/gafcore/checkout-confirm',
  path: '/api/gafcore/checkout-confirm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/gafcore': typeof GafcoreRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/gafcore/app': typeof GafcoreAppRoute
  '/gafcore/login': typeof GafcoreLoginRoute
  '/gafcore/projects': typeof GafcoreProjectsRoute
  '/gafcore/register': typeof GafcoreRegisterRoute
  '/api/v1/credits': typeof ApiV1CreditsRoute
  '/api/v1/generations': typeof ApiV1GenerationsRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/keys': typeof ApiV1KeysRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/gafcore/settings/project': typeof GafcoreSettingsProjectRoute
  '/api/gafcore/chat/stream': typeof ApiGafcoreChatStreamRoute
  '/api/gafcore/checkout-session': typeof ApiGafcoreCheckoutSessionRoute
  '/api/gafcore/checkout-confirm': typeof ApiGafcoreCheckoutConfirmRoute
  '/api/public/billing/check': typeof ApiPublicBillingCheckRoute
  '/api/public/gafcore/support-faq': typeof ApiPublicGafcoreSupportFaqRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/v1/ai/generate': typeof ApiV1AiGenerateRoute
  '/api/v1/keys/$id': typeof ApiV1KeysIdRoute
  '/api/v1/openapi/json': typeof ApiV1OpenapiJsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/gafcore': typeof GafcoreRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/gafcore/app': typeof GafcoreAppRoute
  '/gafcore/login': typeof GafcoreLoginRoute
  '/gafcore/projects': typeof GafcoreProjectsRoute
  '/gafcore/register': typeof GafcoreRegisterRoute
  '/api/v1/credits': typeof ApiV1CreditsRoute
  '/api/v1/generations': typeof ApiV1GenerationsRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/keys': typeof ApiV1KeysRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/gafcore/settings/project': typeof GafcoreSettingsProjectRoute
  '/api/gafcore/chat/stream': typeof ApiGafcoreChatStreamRoute
  '/api/gafcore/checkout-session': typeof ApiGafcoreCheckoutSessionRoute
  '/api/gafcore/checkout-confirm': typeof ApiGafcoreCheckoutConfirmRoute
  '/api/public/billing/check': typeof ApiPublicBillingCheckRoute
  '/api/public/gafcore/support-faq': typeof ApiPublicGafcoreSupportFaqRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/v1/ai/generate': typeof ApiV1AiGenerateRoute
  '/api/v1/keys/$id': typeof ApiV1KeysIdRoute
  '/api/v1/openapi/json': typeof ApiV1OpenapiJsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/gafcore': typeof GafcoreRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/gafcore_/app': typeof GafcoreAppRoute
  '/gafcore_/login': typeof GafcoreLoginRoute
  '/gafcore_/projects': typeof GafcoreProjectsRoute
  '/gafcore_/register': typeof GafcoreRegisterRoute
  '/api/v1/credits': typeof ApiV1CreditsRoute
  '/api/v1/generations': typeof ApiV1GenerationsRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/keys': typeof ApiV1KeysRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/gafcore_/settings/project': typeof GafcoreSettingsProjectRoute
  '/api/gafcore/chat/stream': typeof ApiGafcoreChatStreamRoute
  '/api/gafcore/checkout-session': typeof ApiGafcoreCheckoutSessionRoute
  '/api/gafcore/checkout-confirm': typeof ApiGafcoreCheckoutConfirmRoute
  '/api/public/billing/check': typeof ApiPublicBillingCheckRoute
  '/api/public/gafcore/support-faq': typeof ApiPublicGafcoreSupportFaqRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/v1/ai/generate': typeof ApiV1AiGenerateRoute
  '/api/v1/keys/$id': typeof ApiV1KeysIdRoute
  '/api/v1/openapi/json': typeof ApiV1OpenapiJsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/credits'
    | '/gafcore'
    | '/login'
    | '/privacy'
    | '/refund'
    | '/register'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/api/chat'
    | '/gafcore/app'
    | '/gafcore/login'
    | '/gafcore/projects'
    | '/gafcore/register'
    | '/api/v1/credits'
    | '/api/v1/generations'
    | '/api/v1/health'
    | '/api/v1/keys'
    | '/api/v1/me'
    | '/gafcore/settings/project'
    | '/api/gafcore/chat/stream'
    | '/api/gafcore/checkout-session'
    | '/api/gafcore/checkout-confirm'
    | '/api/public/billing/check'
    | '/api/public/gafcore/support-faq'
    | '/api/public/payments/webhook'
    | '/api/v1/ai/generate'
    | '/api/v1/keys/$id'
    | '/api/v1/openapi/json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/credits'
    | '/gafcore'
    | '/login'
    | '/privacy'
    | '/refund'
    | '/register'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/api/chat'
    | '/gafcore/app'
    | '/gafcore/login'
    | '/gafcore/projects'
    | '/gafcore/register'
    | '/api/v1/credits'
    | '/api/v1/generations'
    | '/api/v1/health'
    | '/api/v1/keys'
    | '/api/v1/me'
    | '/gafcore/settings/project'
    | '/api/gafcore/chat/stream'
    | '/api/gafcore/checkout-session'
    | '/api/gafcore/checkout-confirm'
    | '/api/public/billing/check'
    | '/api/public/gafcore/support-faq'
    | '/api/public/payments/webhook'
    | '/api/v1/ai/generate'
    | '/api/v1/keys/$id'
    | '/api/v1/openapi/json'
  id:
    | '__root__'
    | '/'
    | '/credits'
    | '/gafcore'
    | '/login'
    | '/privacy'
    | '/refund'
    | '/register'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/api/chat'
    | '/gafcore_/app'
    | '/gafcore_/login'
    | '/gafcore_/projects'
    | '/gafcore_/register'
    | '/api/v1/credits'
    | '/api/v1/generations'
    | '/api/v1/health'
    | '/api/v1/keys'
    | '/api/v1/me'
    | '/gafcore_/settings/project'
    | '/api/gafcore/chat/stream'
    | '/api/gafcore/checkout-session'
    | '/api/gafcore/checkout-confirm'
    | '/api/public/billing/check'
    | '/api/public/gafcore/support-faq'
    | '/api/public/payments/webhook'
    | '/api/v1/ai/generate'
    | '/api/v1/keys/$id'
    | '/api/v1/openapi/json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreditsRoute: typeof CreditsRoute
  GafcoreRoute: typeof GafcoreRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  GafcoreAppRoute: typeof GafcoreAppRoute
  GafcoreLoginRoute: typeof GafcoreLoginRoute
  GafcoreProjectsRoute: typeof GafcoreProjectsRoute
  GafcoreRegisterRoute: typeof GafcoreRegisterRoute
  ApiV1CreditsRoute: typeof ApiV1CreditsRoute
  ApiV1GenerationsRoute: typeof ApiV1GenerationsRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1KeysRoute: typeof ApiV1KeysRouteWithChildren
  ApiV1MeRoute: typeof ApiV1MeRoute
  GafcoreSettingsProjectRoute: typeof GafcoreSettingsProjectRoute
  ApiGafcoreChatStreamRoute: typeof ApiGafcoreChatStreamRoute
  ApiGafcoreCheckoutSessionRoute: typeof ApiGafcoreCheckoutSessionRoute
  ApiGafcoreCheckoutConfirmRoute: typeof ApiGafcoreCheckoutConfirmRoute
  ApiPublicBillingCheckRoute: typeof ApiPublicBillingCheckRoute
  ApiPublicGafcoreSupportFaqRoute: typeof ApiPublicGafcoreSupportFaqRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiV1AiGenerateRoute: typeof ApiV1AiGenerateRoute
  ApiV1OpenapiJsonRoute: typeof ApiV1OpenapiJsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gafcore': {
      id: '/gafcore'
      path: '/gafcore'
      fullPath: '/gafcore'
      preLoaderRoute: typeof GafcoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gafcore_/register': {
      id: '/gafcore_/register'
      path: '/gafcore/register'
      fullPath: '/gafcore/register'
      preLoaderRoute: typeof GafcoreRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gafcore_/projects': {
      id: '/gafcore_/projects'
      path: '/gafcore/projects'
      fullPath: '/gafcore/projects'
      preLoaderRoute: typeof GafcoreProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gafcore_/login': {
      id: '/gafcore_/login'
      path: '/gafcore/login'
      fullPath: '/gafcore/login'
      preLoaderRoute: typeof GafcoreLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gafcore_/app': {
      id: '/gafcore_/app'
      path: '/gafcore/app'
      fullPath: '/gafcore/app'
      preLoaderRoute: typeof GafcoreAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gafcore_/settings/project': {
      id: '/gafcore_/settings/project'
      path: '/gafcore/settings/project'
      fullPath: '/gafcore/settings/project'
      preLoaderRoute: typeof GafcoreSettingsProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/me': {
      id: '/api/v1/me'
      path: '/api/v1/me'
      fullPath: '/api/v1/me'
      preLoaderRoute: typeof ApiV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/keys': {
      id: '/api/v1/keys'
      path: '/api/v1/keys'
      fullPath: '/api/v1/keys'
      preLoaderRoute: typeof ApiV1KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/generations': {
      id: '/api/v1/generations'
      path: '/api/v1/generations'
      fullPath: '/api/v1/generations'
      preLoaderRoute: typeof ApiV1GenerationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/credits': {
      id: '/api/v1/credits'
      path: '/api/v1/credits'
      fullPath: '/api/v1/credits'
      preLoaderRoute: typeof ApiV1CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/openapi/json': {
      id: '/api/v1/openapi/json'
      path: '/api/v1/openapi/json'
      fullPath: '/api/v1/openapi/json'
      preLoaderRoute: typeof ApiV1OpenapiJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/keys/$id': {
      id: '/api/v1/keys/$id'
      path: '/$id'
      fullPath: '/api/v1/keys/$id'
      preLoaderRoute: typeof ApiV1KeysIdRouteImport
      parentRoute: typeof ApiV1KeysRoute
    }
    '/api/v1/ai/generate': {
      id: '/api/v1/ai/generate'
      path: '/api/v1/ai/generate'
      fullPath: '/api/v1/ai/generate'
      preLoaderRoute: typeof ApiV1AiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gafcore/support-faq': {
      id: '/api/public/gafcore/support-faq'
      path: '/api/public/gafcore/support-faq'
      fullPath: '/api/public/gafcore/support-faq'
      preLoaderRoute: typeof ApiPublicGafcoreSupportFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/check': {
      id: '/api/public/billing/check'
      path: '/api/public/billing/check'
      fullPath: '/api/public/billing/check'
      preLoaderRoute: typeof ApiPublicBillingCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gafcore/chat/stream': {
      id: '/api/gafcore/chat/stream'
      path: '/api/gafcore/chat/stream'
      fullPath: '/api/gafcore/chat/stream'
      preLoaderRoute: typeof ApiGafcoreChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gafcore/checkout-session': {
      id: '/api/gafcore/checkout-session'
      path: '/api/gafcore/checkout-session'
      fullPath: '/api/gafcore/checkout-session'
      preLoaderRoute: typeof ApiGafcoreCheckoutSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gafcore/checkout-confirm': {
      id: '/api/gafcore/checkout-confirm'
      path: '/api/gafcore/checkout-confirm'
      fullPath: '/api/gafcore/checkout-confirm'
      preLoaderRoute: typeof ApiGafcoreCheckoutConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiV1KeysRouteChildren {
  ApiV1KeysIdRoute: typeof ApiV1KeysIdRoute
}

const ApiV1KeysRouteChildren: ApiV1KeysRouteChildren = {
  ApiV1KeysIdRoute: ApiV1KeysIdRoute,
}

const ApiV1KeysRouteWithChildren = ApiV1KeysRoute._addFileChildren(
  ApiV1KeysRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreditsRoute: CreditsRoute,
  GafcoreRoute: GafcoreRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  GafcoreAppRoute: GafcoreAppRoute,
  GafcoreLoginRoute: GafcoreLoginRoute,
  GafcoreProjectsRoute: GafcoreProjectsRoute,
  GafcoreRegisterRoute: GafcoreRegisterRoute,
  ApiV1CreditsRoute: ApiV1CreditsRoute,
  ApiV1GenerationsRoute: ApiV1GenerationsRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1KeysRoute: ApiV1KeysRouteWithChildren,
  ApiV1MeRoute: ApiV1MeRoute,
  GafcoreSettingsProjectRoute: GafcoreSettingsProjectRoute,
  ApiGafcoreChatStreamRoute: ApiGafcoreChatStreamRoute,
  ApiGafcoreCheckoutSessionRoute: ApiGafcoreCheckoutSessionRoute,
  ApiGafcoreCheckoutConfirmRoute: ApiGafcoreCheckoutConfirmRoute,
  ApiPublicBillingCheckRoute: ApiPublicBillingCheckRoute,
  ApiPublicGafcoreSupportFaqRoute: ApiPublicGafcoreSupportFaqRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiV1AiGenerateRoute: ApiV1AiGenerateRoute,
  ApiV1OpenapiJsonRoute: ApiV1OpenapiJsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
